#!/bin/sh
readonly INFILE="$1"
readonly OUTFILE="$INFILE.c"

# We need the ridiculous amount of escaping because
# of the two layers of string interpolation going on
REQUIRED_HEADERS_AND_TYPEDEFS="#include <stdio.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>

typedef char* string;
typedef uint64_t nat;

char *__slice__(char* str, int start, int end)
{
	int len = end - start + 1;

	char *res = malloc(sizeof(char) * len + 1);
	res[len] = '\\\\0';

	memcpy(res, str+start, len);

	return res;
}

"

sed "s,^ \+\(requires\|invariant\|decreases\|ensures\),// \1,;
    s/^ \+var//g;
    s/^\(method\|function\|predicate\) //;
    s,^\(\w\+(.\+)\) returns (\(\w\+\): \(\w\+\)),\3 \1\n// TODO declare \3 \2,;
    s/:=/=/g;
    s/\(\w\+\): \(\w\+\)/\2 \1/g;
    s/\(\w\+\)\[\(.*\?\)\.\.]/__slice__(\1, \2, strlen(\1))/;
    s/\(\w\+\)\[\.\.\(.*\?\)]/__slice__(\1, 0, \2)/;
    s/\(\w\+\)\[\(.*\?\)\.\.\(.*\?\)]/__slice__(\1, \2, \3)/;
    s/|\(\w\+\)|/strlen(\1)/g" "$INFILE" \
        | echo "$REQUIRED_HEADERS_AND_TYPEDEFS$(cat -)" > "$OUTFILE"
